"""initial_mysql_migration

Revision ID: dc1466d53570
Revises: 
Create Date: 2025-05-14 15:19:07.494894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1466d53570'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_id'), ['id'], unique=False)

    op.create_table('productos',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=36), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_descripcion'), ['descripcion'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_marca'), ['marca'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_marca'))
        batch_op.drop_index(batch_op.f('ix_productos_descripcion'))
        batch_op.drop_index(batch_op.f('ix_productos_codigo'))

    op.drop_table('productos')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_id'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
